baseURL: "/"
defaultContentLanguage: pt
languageCode:    "pt-br"
theme: "airspace"
disableKinds:
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
enableRobotsTXT: false
metaDataFormat:  "yaml"
enableMissingTranslationPlaceholders: true
disableFastRender: true
ignoreFiles: [ "\\.tmp$", "\\.tmp\\-browserify" ]
stepAnalysis: true
templateMetrics: true
pluralizeListTitles: false
googleAnalytics: ""
buildFuture: true
FootnoteReturnLinkContents: "↩"
taxonomies:
  role: "role"
# languages:
#   pt:
#     contentDir: content/portuguese
#     languageName: Português
#     languageCode: "pt-br"
#     title: "Titulo Aqui"
#     weight: 1
#     params:
#       description: "Descricao do site"
#     menu:
#       main:
#           - Name: "Sobre"
#             Pre: ""
#             Weight: 1
#             Identifier: "sobre"
#             URL: "/sobre"
#           - Name: "Blog"
#             Pre: ""
#             Weight: 2
#             Identifier: "blog"
#             URL: "/blog"
#           - Name: "Contato"
#             Pre: ""
#             Weight: 3
#             Identifier: "contato"
#             URL: "/contato"
params:
  authorName:    "Stephanie de Castro"
  gitHubUser:    "stephaniecastron"