name: Deploy Prod

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.0]

    steps:
    - uses: actions/checkout@v1
    - name: Install Hugo
      run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD}
      env:
        HUGO_VERSION: 0.69.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, test, build and deploy
      run: |
        npm install -g firebase-tools
        npm install
        npm run build
        hugo --ignoreCache --cleanDestinationDir
        # $HOME/hugo --ignoreCache --cleanDestinationDir
        pwd
        ls
        # firebase deploy --only hosting --token $FIREBASE_TOKEN
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
