name: Deploy Prod

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.0]

    steps:
    - name: Set Docker
      uses: docker://node
    - uses: actions/checkout@v1
    - name: Install Hugo
      run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
      env:
        HUGO_VERSION: 0.69.0
    - name: npm install, test, build and deploy
      run: |
        cd $HOME/hugo
        npm install firebase-tools@8.0.0
        npm install
        npm run build
        firebase deploy --only hosting --token $FIREBASE_TOKEN
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
