name: Deploy Prod

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.0]

    steps:
    - name: Set Docker
      uses: docker://node
    - uses: actions/checkout@v1
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.69.'
    - name: npm install, test, build and deploy
      run: |
        npm install firebase-tools@8.0.0
        npm install
        npm run build
        firebase deploy --only hosting --token $FIREBASE_TOKEN
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
